// Knowledge base, part 5: Stock Market University (education only). Rules checked October 2026.
export const STOCK_CARDS = [
["stock-university", "Stock Market University (in the app)", "stock market university stocks trading course freelance tab learn invest modules calculator",
 "Inside the Freelance tab, the Stock Market University pill is a free 10-module course: how stocks work, opening a brokerage account, order types, reading a stock, investing vs trading, risk management, day trading and US rules, taxes, tips and mistakes, and scams. It has a position size calculator, a glossary and official links (SEC, FINRA, IRS, SIPC). It is education only. Cindy cannot tell anyone what to buy or sell, cannot place trades and is not a licensed adviser or broker."],
["stock-basics", "Stocks, ETFs and how markets work", "stock share etf index fund nyse nasdaq market hours premarket dividend capital gain",
 "A share is partial ownership of a company. You can gain from a rising price or dividends and you can lose money, even all of it. US markets are open 9:30 a.m. to 4 p.m. Eastern on weekdays, with thinner pre-market and after-hours sessions. ETFs and index funds hold many stocks at once and are usually the lower-risk starting point for beginners compared with single stocks."],
["stock-broker-account", "Opening a brokerage account", "brokerage account broker open cash margin sipc finra brokercheck age 18 ira custodial",
 "Use a SIPC-member, FINRA-registered broker (check at brokercheck.finra.org). You must be 18 to open your own account; custodial accounts exist for minors. A cash account trades only with your own money; a margin account borrows and can lose more than you deposited, so beginners should start with cash. SIPC protects assets if a brokerage fails (up to 500,000 dollars including 250,000 dollars of cash) but not against losses from price drops. Never share logins or send money to someone who contacts you with a tip."],
["stock-order-types", "Order types and settlement", "market order limit order stop loss stop limit gtc day order bid ask spread settlement t+1 good faith",
 "A market order fills now at the best price available; a limit order only fills at your price or better; a stop order becomes a market order when the stop price is hit, and gaps can fill worse than the stop. Bid is what buyers offer, ask is what sellers want, and the spread is a cost. US stocks settle one business day after the trade (T+1, since May 28, 2024). Beginners generally should use limit orders."],
["stock-day-trading-rules", "Day trading and the pattern day trader rule", "day trading pattern day trader pdt 25000 finra 4210 intraday margin june 2026 margin call",
 "The old pattern day trader rule (four or more day trades in five business days in a margin account needed 25,000 dollars) was eliminated: the SEC approved FINRA's change in April 2026 and the 25,000 dollar minimum and PDT label ended effective June 4, 2026, replaced by intraday margin standards under FINRA Rule 4210. Brokers have until October 20, 2027 to transition and many set their own limits, so read your broker's policy. Margin still magnifies losses and can trigger margin calls. Day trading is the riskiest style; research on real day traders finds most lose money. Check finra.org and sec.gov for current rules."],
["stock-risk", "Risk management and position sizing", "risk management position size stop loss 1 percent reward risk journal paper trading penny stock leverage options",
 "Decide the most you'll risk per trade before entering; a common rule of thumb is 1 percent of the account or less. Position size equals account size times risk percent, divided by the difference between entry and stop price. Set a daily loss limit, avoid revenge trading, keep a journal, paper trade first, and avoid thin penny stocks, leveraged and inverse ETFs and options until you truly understand them. Never invest your rent, emergency fund or borrowed money. The app has a position size calculator."],
["stock-taxes", "US taxes on stocks and trading", "stock taxes capital gains short term long term wash sale 1099-b 8949 schedule d loss 3000 trader tax status mark to market net investment income",
 "Gains on stock held one year or less are short-term and taxed as ordinary income; held more than a year they're long-term at 0, 15 or 20 percent. For 2026 the 0 percent rate covers taxable income up to about 49,450 dollars single or 98,900 married filing jointly, and 20 percent begins above about 545,500 single or 613,700 joint; high earners may also owe the 3.8 percent net investment income tax. Capital losses offset gains and up to 3,000 dollars a year against other income, with the rest carried forward. The wash sale rule disallows a loss if you buy the same or a substantially identical security within 30 days before or after the sale. Brokers send Form 1099-B; you report on Form 8949 and Schedule D. Trader tax status and the mark-to-market election are for full-time traders and need a CPA. Nobody withholds tax on trading, so you may owe quarterly estimates. Confirm amounts at irs.gov."],
["stock-illegal", "Illegal trading practices and scams", "insider trading manipulation pump and dump spoofing wash trading scam fake app whatsapp telegram guaranteed returns sec",
 "Illegal: insider trading (trading on material non-public information), market manipulation such as spoofing, wash trading and pump-and-dump schemes, and front-running. Scam signs: guaranteed returns, secret strategies, pressure to deposit today, someone who contacted you first on WhatsApp, Telegram or a dating app, and fake trading apps that block withdrawals. Verify advisers at adviserinfo.sec.gov and brokers at BrokerCheck, and report fraud at sec.gov/tcr and reportfraud.ftc.gov."],
["stock-research", "Researching a stock", "research fundamentals technical analysis edgar 10-k 10-q 8-k pe ratio market cap volume chart earnings",
 "Read free filings on SEC EDGAR: the 10-K (annual), 10-Q (quarterly) and 8-K (major events). Look at revenue growth, profit, debt and cash. The P/E ratio is price over earnings per share and means more when compared with the company's history and industry. Technical analysis (charts, moving averages, support and resistance) helps with timing and risk limits but can't predict prices. Prices can jump on earnings announcements."]
];
